server:
  port: 8086
  servlet:
    context-path: /spring-cloud-oauth2


spring:
  redis:
    host: 47.113.88.115
    #redis端口
    port: 6379
    #redis超时时间（毫秒），如果不设置，取默认值2000
    timeout: 10000

  main:
    allow-bean-definition-overriding: true

 # datasource:
  #  driver-class-name: com.mysql.cj.jdbc.Driver
   # type: com.alibaba.druid.pool.DruidDataSource
    #url: jdbc:mysql://127.0.0.1:3306/oauth-center?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    #username: root
    #password: 123456

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.jason.oauth.model
  global-config:
    db-config:
      id-type: auto



