version: '3'
services:
  spring-security-service:
    image: jason/spring-security:latest
    restart: always
    container_name: spring-security
    environment:
      - spring.profiles.active=dev
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8087:8087