server:
  port: 8088

spring:
  freemarker:
    templateLoaderPath: classpath:/static/
    suffix: .ftl
    charset: UTF-8
    request-context-attribute: request

  redis:
    host: 47.113.88.115
    #redis端口
    port: 6379
    #redis超时时间（毫秒），如果不设置，取默认值2000
    timeout: 10000


jwt:
  # 加密秘钥
  secret: HZa64EK1MgX0DssZOTZdeMWh6QIea9ic
  # token有效时长，7天，单位秒  暂时更改为1天 24*3600 = 86400
  expire: 86400
  header: token

websocket:
  type: spring

lock:
  type: redis

