version: '3'
services:
  spring-mvc-service:
    image: jason/spring-mvc:latest
    restart: always
    container_name: spring-mvc
    environment:
      - spring.profiles.active=dev
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8088:8088