version: '3'
services:
  spring-cloud-gateway-service:
    image: jason/spring-cloud-gateway:latest
    restart: always
    container_name: spring-cloud-gateway
    environment:
      - spring.profiles.active=dev
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8085:8085