version: '3'
services:
  spring-cloud-oauth2-service:
    image: jason/spring-cloud-oauth2:latest
    restart: always
    container_name: spring-cloud-oauth2
    environment:
      - spring.profiles.active=dev
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8086:8086